### ISSUE TITLE
Plot u and w to check that the streamfunction calculation makes sense

### ISSUE THREAD

**Issue by ikeshwani** [ikeshwani/HorizontalConvection#29]
streamfunction calculation: issue #27 

$$ \frac{d\psi}{dz} = \int u dy ,- \frac{d\psi}{dx} =   \int w dy $$

derivative of \psi should match up with the expected signs of u and w

**Comment by hdrake** [comment]
I think the $\int z \text{d}y$ should be $\int w \text{d}y$ but otherwise great idea to open this issue!

**Comment by ikeshwani** [comment]
so true

**Comment by ikeshwani** [comment]
![download-26](https://github.com/user-attachments/assets/8673b4e6-cfe0-4c10-afdd-9e41e061ce53)

**Comment by ikeshwani** [comment]
![download-27](https://github.com/user-attachments/assets/cbd958b8-e877-433a-9843-b8148f15fd20)
