### ISSUE TITLE
Overlay buoyancy contours on streamfunction heatmap 

### ISSUE THREAD

**Issue by ikeshwani** [ikeshwani/HorizontalConvection#30]
refer to issue #27

**Comment by ikeshwani** [comment]
![download-24](https://github.com/user-attachments/assets/f8ffc0e9-7d6a-4869-b9bc-b766d9e32ca2)

@hdrake this looks pretty cool

**Comment by hdrake** [comment]
Yes, very cool! A few improvements:
1) Add inline labels for the contours https://docs.juliaplots.org/latest/series_types/contour/#Common-Attributes
2) Made the contour lines thicker
3) Turn the streamfunction values in the hills from zero to `NaN` so that the contours behave correctly near them.

**Comment by ikeshwani** [comment]
![download-25](https://github.com/user-attachments/assets/763b5d7e-3f23-4f8d-8731-d03b563443e0)

my attempt @hdrake

**Comment by hdrake** [comment]
Very nice! I'm not sure why the contours are still showing up along the boundaries of the hills, but that's a detail we can fix another time.

The structure of the -0.47 contour is so interesting!!
