### ISSUE TITLE
Add potential energy plot versus time to the animation

### ISSUE THREAD

**Issue by ikeshwani** [ikeshwani/HorizontalConvection#8]
Use the potential energy timeseries as seen here:

https://github.com/ikeshwani/HorizontalConvection/blob/00ea1c35bdd9fc2c6f0215b2f34b2a057b907a0c/src/plot_hilly_horizontal_convection.jl#L116

**Comment by hdrake** [comment]
Addressed by https://github.com/ikeshwani/HorizontalConvection/blob/8c01005bbfea5950a6622fc46acd3c6ec3bd72c1/src/simulation.jl#L20-L26
Can close this issue.

**Comment by hdrake** [comment]
@ikeshwani, you can close this issue now.
